services:

  mysql:
    image: mysql:8.0
    container_name: cloudnotes-mysql

    environment:
      MYSQL_ROOT_PASSWORD: cloudnotes_root
      MYSQL_DATABASE: cloudnotes
      MYSQL_USER: cloudnotes_user
      MYSQL_PASSWORD: cloudnotes_pass

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped

volumes:
  mysql_data: